services:
  - type: web
    name: mini-blog
    env: python
    startCommand: gunicorn app:app
    buildCommand: pip install -r requirements.txt
    plan: free

cronJobs:
  - name: backup-db
    schedule: "@daily"
    command: python backup.py
