services:
  - type: web
    name: mini-blog
    env: python
    startCommand: gunicorn --chdir . app:app # ĐÃ SỬA
    buildCommand: pip install gunicorn flask python-dotenv secure-smtplib # ĐÃ SỬA TRƯỚC ĐÓ
    plan: free
#...
