services:
  - type: web
    name: mini-blog
    env: python
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    buildCommand: pip install flask python-dotenv secure-smtplib
    plan: free

cronJobs:
