services:
  - type: web
    name: mini-blog
    env: python
    startCommand: python -m gunicorn app:app
    buildCommand: pip install gunicorn flask python-dotenv secure-smtplib # ĐÃ SỬA TRƯỚC ĐÓ
    plan: free

cronJobs:
# ... (các dòng khác giữ nguyên)
